# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GerarRelatorioMFeFgP.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtWidgets import *
from PySide2.QtWidgets import QTabWidget


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(592, 551)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 591, 551))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 40, 51, 17))
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 220, 91, 17))
        self.textEdit = QTextEdit(self.tab)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 250, 571, 231))
        self.label_33 = QLabel(self.tab)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 10, 81, 21))
        self.pushButton_3 = QPushButton(self.tab)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(500, 10, 81, 25))
        self.lineEdit_7 = QLineEdit(self.tab)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(90, 10, 411, 25))
        self.lineEdit_8 = QLineEdit(self.tab)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(70, 40, 511, 25))

        #Botões de Ok e Cancelar - Relatório Simples
        self.buttonBox = QDialogButtonBox(self.tab)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(410, 490, 171, 25))
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)


        self.lineEdit_9 = QLineEdit(self.tab)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(60, 130, 521, 25))
        self.dateEdit_3 = QDateEdit(self.tab)
        self.dateEdit_3.setObjectName(u"dateEdit_3")
        self.dateEdit_3.setGeometry(QRect(110, 160, 111, 31))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 160, 101, 31))
        self.label_34 = QLabel(self.tab)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 130, 41, 17))
        self.label_41 = QLabel(self.tab)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 70, 121, 21))
        self.lineEdit_15 = QLineEdit(self.tab)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(130, 70, 451, 25))
        self.label_43 = QLabel(self.tab)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 100, 81, 17))
        self.label_44 = QLabel(self.tab)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(350, 100, 81, 21))
        self.lineEdit_18 = QLineEdit(self.tab)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(100, 100, 241, 25))
        self.lineEdit_19 = QLineEdit(self.tab)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(430, 100, 151, 25))
        self.line_2 = QFrame(self.tab)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 200, 571, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 40, 51, 17))
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 101, 21))
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 100, 121, 21))
        self.label = QLabel(self.tab_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 130, 101, 21))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 10, 71, 17))
        self.textEdit_2 = QTextEdit(self.tab_2)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(10, 380, 571, 101))
        self.lineEdit = QLineEdit(self.tab_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(90, 10, 411, 25))
        self.lineEdit_2 = QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(60, 40, 271, 25))
        self.dateEdit = QDateEdit(self.tab_2)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(120, 100, 111, 26))
        self.timeEdit = QTimeEdit(self.tab_2)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setGeometry(QRect(370, 100, 121, 26))
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(180, 130, 61, 21))
        self.pushButton = QPushButton(self.tab_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(500, 10, 81, 25))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 160, 51, 21))
        self.lineEdit_5 = QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(60, 160, 521, 25))
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(310, 130, 201, 21))
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 190, 251, 21))
        self.doubleSpinBox = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(110, 130, 65, 26))
        self.doubleSpinBox_2 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(240, 130, 65, 26))
        self.doubleSpinBox_3 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        self.doubleSpinBox_3.setGeometry(QRect(510, 130, 71, 26))
        self.doubleSpinBox_4 = QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_4.setObjectName(u"doubleSpinBox_4")
        self.doubleSpinBox_4.setGeometry(QRect(260, 190, 65, 26))

        # Botões de Ok e Cancelar - Relatório Completo
        self.buttonBox_2 = QDialogButtonBox(self.tab_2)
        self.buttonBox_2.setObjectName(u"buttonBox_2")
        self.buttonBox_2.setGeometry(QRect(420, 490, 166, 25))
        self.buttonBox_2.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
        self.buttonBox_2.accepted.connect(Dialog.accept)
        self.buttonBox_2.rejected.connect(Dialog.reject)

        self.label_35 = QLabel(self.tab_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(340, 40, 121, 21))
        self.lineEdit_10 = QLineEdit(self.tab_2)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(460, 40, 121, 25))
        self.line = QFrame(self.tab_2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 340, 571, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_36 = QLabel(self.tab_2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 360, 91, 17))
        self.label_37 = QLabel(self.tab_2)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 250, 67, 17))
        self.label_38 = QLabel(self.tab_2)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 280, 61, 21))
        self.label_39 = QLabel(self.tab_2)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 220, 221, 21))
        self.lineEdit_11 = QLineEdit(self.tab_2)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(230, 220, 351, 25))
        self.lineEdit_12 = QLineEdit(self.tab_2)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(80, 250, 501, 25))
        self.lineEdit_13 = QLineEdit(self.tab_2)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(70, 280, 511, 25))
        self.label_40 = QLabel(self.tab_2)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 310, 171, 21))
        self.lineEdit_14 = QLineEdit(self.tab_2)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(180, 310, 401, 25))
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 81, 17))
        self.label_42 = QLabel(self.tab_2)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(340, 70, 81, 21))
        self.lineEdit_16 = QLineEdit(self.tab_2)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(100, 70, 231, 25))
        self.lineEdit_17 = QLineEdit(self.tab_2)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(420, 70, 161, 25))
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(Dialog)

    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Motor:", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Observa\u00e7\u00f5es:", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"Salvar em:", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Selecionar", None))
        self.lineEdit_9.setText("")
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Data do Teste:", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"Local:", None))
        self.label_41.setText(QCoreApplication.translate("Dialog", u"Classe do Motor:", None))
        self.label_43.setText(QCoreApplication.translate("Dialog", u"Propelente:", None))
        self.label_44.setText(QCoreApplication.translate("Dialog", u"Propor\u00e7\u00e3o:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Relat\u00f3rio Simples", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Motor:", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Data do Teste:", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Hor\u00e1rio do Teste:", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Temperatura:", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Salvar em:", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"Press\u00e3o:", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Selecionar", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Local:", None))
        self.lineEdit_5.setText("")
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Altitude em Rela\u00e7\u00e3o ao Mar:", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Frequ\u00eancia de Aquisi\u00e7\u00e3o dos Dados:", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"Classe do Motor:", None))
        self.label_36.setText(QCoreApplication.translate("Dialog", u"Observa\u00e7\u00f5es:", None))
        self.label_37.setText(QCoreApplication.translate("Dialog", u"Bancada:", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"Igni\u00e7\u00e3o:", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"Sistema de Aquisi\u00e7\u00e3o de Dados:", None))
        self.lineEdit_11.setText("")
        self.lineEdit_12.setText("")
        self.lineEdit_13.setText("")
        self.label_40.setText(QCoreApplication.translate("Dialog", u"Tipo de C\u00e9lula de Carga:", None))
        self.lineEdit_14.setText("")
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Propelente:", None))
        self.label_42.setText(QCoreApplication.translate("Dialog", u"Propor\u00e7\u00e3o:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Relat\u00f3rio Completo", None))
    # retranslateUi

